springdoc:
  api-docs:
    path: /v3/api-docs  # JSON 문서 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
    operationsSorter: alpha  # 알파벳 순서로 API 정렬
    tagsSorter: alpha


server:
  servlet:
    session:
      cookie:
        name: JSESSIONID

spring:
  profiles:
    active: aws

  datasource:
    url: jdbc:mysql://localhost:3306/hstagram
    username: root
    password: 940627Ghkd!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  data:
   redis:
     host: 127.0.0.1
     port: 6379

  session:
    store-type: redis
    timeout: 30m  # 세션 만료 시간 (30분)
    redis:
      flush-mode: on_save
      namespace: spring:session  # Redis에 저장되는 키의 prefix

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
